### PR TITLE
Docker and deploy

### PR DESCRIPTION
**Pull request by luizcarloscf**
I'm looking for a way to generate the docs excluding the part about data types. So, I preferred to remove this from the code in the meanwhile. I think it doesn't makes much sense keeping the docs in this repository, what is your opinion?

About the kubernetes deployment, it was used to see if everything is working as supposed to be. 

To build the images docker, I followed the way the other repositories implementation, as is-skeletons-detector or is-skeletons-heatmap, and I save the image in my dockerhub. I think maybe it's better if it were a simple dockerfile with a build-step, so I can make the auto build in my dockerhub.

I was a little confused about two profiles in dockerhub, labviros and viros. And why is there no autobuild for python projects?

### CODE REVIEW

**Comment by felippe-mendonca** [comment]
> I'm looking for a way to generate the docs excluding the part about data types. So, I preferred to remove this from the code in the meanwhile. I think it doesn't makes much sense keeping the docs in this repository, what is your opinion?

Take a look at the [protobuf's plugin do generate docs](https://github.com/pseudomuto/protoc-gen-doc) if there's a option to remove the data types description. If not, try to remove using a `sed` command to get the initial line of this part. You can make magic with bash commands! If you can't automatize it, simply generate the docs, cut and paste on README and include a small description on how to generate that documentation about protobuf message.

> About the kubernetes deployment, it was used to see if everything is working as supposed to be.

k8s manifests (deployment, service, etc) will be a next step, just after having all well consolidated.

> To build the images docker, I followed the way the other repositories implementation, as is-skeletons-detector or is-skeletons-heatmap, and I save the image in my dockerhub. I think maybe it's better if it were a simple dockerfile with a build-step, so I can make the auto build in my dockerhub.

To make your Dockerfile you can take a look at [how-to](https://github.com/labviros/how-to), on how to deploy a app on k8s folder. What you have done: create tow images, one for development purpose and another for deployment, it's only when you need to perform tests during development and you don't want to install any library on your computer.

> I was a little confused about two profiles in dockerhub, labviros and viros. And why is there no autobuild for python projects?

viros dockerhub was created when docker didn't offer corporation approach, it's a simple account. labviros is a corporation account, that can has people associated to.

**Comment by luizcarloscf** [comment]
I think that is it. If everything is ok, I insert the description of how generate the documentation.

**Comment by luizcarloscf** [comment]
Instead of using a precompiled binary to generate the docs, I use the docker image (like recommended in  [protobuf's plugin to generate docs](https://github.com/pseudomuto/protoc-gen-doc))

And I noticed the need to clean to ampq channel.

**Comment by felippe-mendonca** [comment]
> Instead of using a precompiled binary to generate the docs, I use the docker image (like recommended in [protobuf's plugin to generate docs](https://github.com/pseudomuto/protoc-gen-doc))

Great! Always read the recommendations! But, I think that you should remove some generated information. In my opinion, I'd leave just what is bellow __options.proto__ marker, changing this title to some thing like "Service configuration". Above of that, insert on a further PR a brief description of the service, containing a link to the detector that you are using, and other information such you can find in this [repo](https://github.com/labviros/is-robot-controller).

Regarding remove/edit the parts of generated docs, always try to do in a script way. Not sure if will be possible to only modify a part of the README, because you are suppose to have more information above, but try to do it in the future.

> And I noticed the need to clean to ampq channel.

Yes, this is necessary to prevent messages being queued. In is-wire c++ version, we've implemented a method called [consume_ready](https://github.com/labviros/is-wire/blob/15812227b57b814fbc9317465b6918375bc89c92/wire/core/channel.cpp#L54), whice retrieves all message accumulated on the local queue. This approach is very useful and could be interesting to also have this feature on Python version. I'm going to accept this PR (since I'd addressed this problem like so), but I'd suggest you to implement the `consume_ready` on is-wire-py, open a PR and call-me to review!

**Review by felippe-mendonca — APPROVED** [review]

**Pull request merged**
